#!/usr/bin/env python
"""A C to Verilog compiler - Command line interface"""

__author__ = "Jon Dawson"
__copyright__ = "Copyright (C) 2012, Jonathan P Dawson"
__version__ = "0.1"

import sys
import os
import subprocess

from chips.compiler.compiler import compile_python_model

if len(sys.argv) < 2 or "help" in sys.argv or "h" in sys.argv:
    print "Usage: csim [options] <input_file>"
    print
    sys.exit(-1)

input_file = sys.argv[-1]
options = sys.argv[1:-1]
model, inputs, outputs, name = compile_python_model(input_file, options)


model.simulation_reset()

while True:
    model.simulation_step()
    if model.instructions[model.program_counter]["op"] == "stop":
        break

