I2
.(dp0
S'inst_1'
p1
(dp2
S'position'
p3
(cnumpy.core.multiarray
scalar
p4
(cnumpy
dtype
p5
(S'f8'
p6
I0
I1
tp7
Rp8
(I3
S'<'
p9
NNNI-1
I-1
I0
tp10
bS'\x00\x00\x00\x00\x00@z\xc0'
p11
tp12
Rp13
g4
(g8
S'\x00\x00\x00\x00\x00\x80a@'
p14
tp15
Rp16
tp17
sS'component'
p18
(dp19
S'inputs'
p20
(dp21
sS'device_inputs'
p22
(dp23
sS'outputs'
p24
(dp25
S'out1'
p26
S'bits'
p27
ssS'device_outputs'
p28
(dp29
sS'source_file'
p30
S'built_in'
p31
sS'file'
p32
S'constant.v'
p33
sS'meta_tags'
p34
(lp35
S'sources'
p36
asS'name'
p37
S'constant_value'
p38
sS'parameters'
p39
(dp40
S'bits'
p41
S'16'
p42
sS'value'
p43
S'0'
p44
ssS'documentation'
p45
S'Constant Value\n==============\n\nOutput constant value repeatedly.\n::\n\n    out1 <= constant\n\n..\n\n +--------------------+-------------------------------------+\n |Language            | Verilog                             |\n +--------------------+-------------------------------------+\n |Synthesis           | Yes                                 |\n +--------------------+-------------------------------------+\n |License             | MIT                                 |\n +--------------------+-------------------------------------+\n |Author              | Jonathan P Dawson                   |\n +--------------------+-------------------------------------+\n |Copyright           | Jonathan P Dawson 2013              |\n +--------------------+-------------------------------------+\n\nParameters\n----------\n\n ============= ============== ==============================================\n Name          Type           Description\n ============= ============== ==============================================\n bits          integer        Data width of out1.\n value         integer        Constant value.\n ============= ============== ==============================================\n\nOutputs\n-------\n\n ============= ============== ==============================================\n Name          Width          Description\n ============= ============== ==============================================\n out1          bits           Output Stream\n ============= ============== ==============================================\n\n'
p46
sS'dependencies'
p47
(lp48
ssg37
g1
sg39
(dp49
g41
g42
sg43
g44
sssS'inst_0'
p50
(dp51
g3
(g4
(g8
S'\x00\x00\x00\x00\x00\x80a\xc0'
p52
tp53
Rp54
g4
(g8
S'\x00\x00\x00\x00\x00\x80a@'
p55
tp56
Rp57
tp58
sg18
(dp59
g20
(dp60
S'in1'
p61
S'bits'
p62
ssg22
(dp63
sg24
(dp64
sg28
(dp65
sg30
S'built_in'
p66
sg32
S'assert.v'
p67
sg34
(lp68
S'sinks'
p69
asg37
S'asserter'
p70
sg39
(dp71
S'bits'
p72
S'16'
p73
ssg45
S'Asserter\n========\n\nRaise an exception if *in1* is 0.\n\n::\n\n    assert(in1)\n\n..\n\n +--------------------+-------------------------------------+\n |Language            | Verilog                             |\n +--------------------+-------------------------------------+\n |Synthesis           | Yes                                 |\n +--------------------+-------------------------------------+\n |License             | MIT                                 |\n +--------------------+-------------------------------------+\n |Author              | Jonathan P Dawson                   |\n +--------------------+-------------------------------------+\n |Copyright           | Jonathan P Dawson 2013              |\n +--------------------+-------------------------------------+\n\nParameters\n----------\n\n ============= ============== ==============================================\n Name          Type           Description\n ============= ============== ==============================================\n bits          integer        Data width of in1.\n ============= ============== ==============================================\n\nInputs\n------\n\n ============= ============== ==============================================\n Name          Width          Description\n ============= ============== ==============================================\n in1           bits           Input Stream\n ============= ============== ==============================================\n\n'
p74
sg47
(lp75
ssg37
g50
sg39
(dp76
S'bits'
p77
S'16'
p78
sss.(dp0
S'inst_1'
p1
(dp2
S'out1'
p3
(cnumpy.core.multiarray
scalar
p4
(cnumpy
dtype
p5
(S'f8'
p6
I0
I1
tp7
Rp8
(I3
S'<'
p9
NNNI-1
I-1
I0
tp10
bS'\x00\x00\x00\x00\x00\x80q\xc0'
p11
tp12
Rp13
g4
(g8
S'\x00\x00\x00\x00\x00\x00d@'
p14
tp15
Rp16
tp17
ssS'inst_0'
p18
(dp19
S'in1'
p20
(g4
(g8
S'\x00\x00\x00\x00\x00\x80a\xc0'
p21
tp22
Rp23
g4
(g8
S'\x00\x00\x00\x00\x00\x00d@'
p24
tp25
Rp26
tp27
ss.(lp0
(S'inst_1'
p1
S'out1'
p2
S'inst_0'
p3
S'in1'
p4
tp5
a.S''
p0
.